### ISSUE TITLE
ValueOf-Unity

### ISSUE THREAD

**Issue by marcusx2** [johanhelsing/OneOf-Unity#1]
Hey man, could you make a Unity version for [this package](https://github.com/mcintyre321/valueof) as well? Don't know how you did it, but thanks for this!

**Comment by johanhelsing** [comment]
Likely you would just have to create a package.json and a .asmdef file.

Unless they used fancy c# features that unity doesn't support, that is.

Looks like it has only one source file, so if what i described above sounds too complicated, maybe just try copying it into your assets folder?

**Comment by marcusx2** [comment]
Ok thanks for the tips!
